# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [92]:
import pandas as pd
import numpy as np




Create a variable a = pd.Series([ 100, 200, 300, 400])

In [93]:
a = pd.Series([100, 200, 300, 400])




Print a, and data type

In [94]:
print(a)




0    100
1    200
2    300
3    400
dtype: int64


Using indexing access the element 300 from the series a.

In [95]:
element = a[2]
print(element)


300


What are the values of index for series a?

In [96]:
print(a.index.values)


[0 1 2 3]


Change the index to  ['c', 'a', 'b', 'd']

In [97]:
a.index = ['c', 'a', 'b', 'd']

Access the value in the series with index 'd'


In [98]:

value = a.loc['d']
print(value)


400


Sort the values wrt to the index and print it
sorted_x2 = np.sort(x2)

print(sorted_x2)

In [99]:

sorted_a = np.sort(a)

print(sorted_a)



[100 200 300 400]


Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [100]:
b = pd.Series([800,450,100], index= ['e','f','g'])
print(b)



e    800
f    450
g    100
dtype: int64


Append b series at the end of a series

In [101]:
combined_series = a._append(b)
print(combined_series)



c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64


In [102]:
#print a again after appending b into it

print(a)



c    100
a    200
b    300
d    400
dtype: int64


Sort the values in descending order of a and print the index of the sorted series

In [103]:
a = np.sort(a)
print(a)



[100 200 300 400]


## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [104]:
df = pd.DataFrame(a, columns=['Values'])
print(df)


   Values
0     100
1     200
2     300
3     400


What is the shape of the datafarme <br>
(also, what does it imply?)

In [105]:

print(df.shape)



(4, 1)


Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column. 

What is the index of the dataframe, is it same as the series 'a' 

In [106]:
# yep its same as the series.



print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [107]:
print(df.head)



<bound method NDFrame.head of    Values
0     100
1     200
2     300
3     400>


In [108]:
print(df.tail)



<bound method NDFrame.tail of    Values
0     100
1     200
2     300
3     400>


Rename the column of the dataframe as 'points'

In [109]:
df = df.rename(columns={'Values': 'points'})
print(df.head())



   points
0     100
1     200
2     300
3     400


Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [110]:
#Create fruits array

fruits = pd.Series(['organge', 'mango', 'apple', 'banana', 'graps', 'watermalon', 'cherry'])
print(fruits)





0       organge
1         mango
2         apple
3        banana
4         graps
5    watermalon
6        cherry
dtype: object


In [121]:
#Create series fruits out of fruits array

fruits = pd.Series(['organge', 'mango', 'apple', 'banana', 'graps', 'watermalon', 'cherry'])
print(fruits)




0       organge
1         mango
2         apple
3        banana
4         graps
5    watermalon
6        cherry
dtype: object


Change the index of fruits to the index of dataframe df

In [ ]:
import pandas as pd

fruits = pd.Series(['orange', 'mango', 'apple', 'banana', 'grapes', 'watermelon', 'cherry'])

target_index = df.index[:len(fruits)]

if len(df) < len(fruits):
    fruits = fruits[:len(df)]
    fruits.index = df.index
else:
    fruits.index = target_index

# 4. Add to the dataframe
df['fruit_name'] = fruits

print(df)



   points fruit_name
0     100     orange
1     200      mango
2     300      apple
3     400     banana


Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [125]:
df['fruits'] = fruits


print(df.head())



   points fruit_name  fruits
0     100     orange  orange
1     200      mango   mango
2     300      apple   apple
3     400     banana  banana


## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2] 

In [126]:
data = {
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
}
d1 = pd.DataFrame(data)
print(d1)



         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2


Print(d1)

In [127]:


print(d1)


         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2


What is the shape of d1.

In [128]:

d1.shape



(5, 2)

Set city = d1['city']

In [ ]:

city = d1['city']


print(city)



<class 'pandas.core.series.Series'>
0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object


print city <br>
What is the type of city.

In [130]:
print(type(city))




<class 'pandas.core.series.Series'>


Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [131]:
data = {
    'city': ['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
    'Temperature': [24,35,36,39]
}
d2 = pd.DataFrame(data)
print(d2)






          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39


print the shape of this dataframe

In [132]:
print(d2.shape)


(4, 2)


merge the two dataframes together, save it in a new dataframe named 'd3'

In [133]:
d3 = pd.concat([d1, d2], ignore_index=True)
print(d3)




          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39


Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there? 

In [135]:
cold_cities = d3[d3['Temperature'] <= 20]

print(cold_cities)


num_cities = len(cold_cities)
print(num_cities)

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
3


Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [136]:
cold_cities1 = d3[d3['Temperature'] >= 30]

print(cold_cities1)




          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39


## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here. 


In [137]:
ut_list = ['Chandigarh', 'Delhi', 'Pondicherry']

def is_ut(city_name):
    if city_name in ut_list:
        return 'Yes'
    else:
        return 'No'


In [139]:
d3['is_ut'] = d3['city'].apply(is_ut)

print(d3)



          city  Temperature is_ut
0   Chandigarh           15   Yes
1        Delhi           22   Yes
2       Kanpur           20    No
3      Chennai           26    No
4       Manali           -2    No
5    Bengalaru           24    No
6   Coimbatore           35    No
7    Srirangam           36    No
8  Pondicherry           39   Yes


The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit. 

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50. 


In [143]:
def c_to_f(c):
    return (c * 9/5) + 32


In [145]:
# check function c_to_f(10)

print({c_to_f(10)})


{50.0}


In [147]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'


d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
print(d3)


          city  Temperature is_ut  Temperature_F  temp_farenhiet
0   Chandigarh           15   Yes           59.0            59.0
1        Delhi           22   Yes           71.6            71.6
2       Kanpur           20    No           68.0            68.0
3      Chennai           26    No           78.8            78.8
4       Manali           -2    No           28.4            28.4
5    Bengalaru           24    No           75.2            75.2
6   Coimbatore           35    No           95.0            95.0
7    Srirangam           36    No           96.8            96.8
8  Pondicherry           39   Yes          102.2           102.2


## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [148]:
ut_list = ['Chandigarh', 'Delhi', 'Pondicherry']

d1_ut = d1[d1['city'].isin(ut_list)]

print(d1_ut)



         city  Temperature
0  Chandigarh           15
1       Delhi           22


Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [ ]:


d3['Temperature_F'] = d3['Temperature'].apply(lambda x: (x * 9/5) + 32)

d3_hot = d3[d3['Temperature_F'] > 90]

print(d3_hot)



          city  Temperature is_ut  Temperature_F  temp_farenhiet
6   Coimbatore           35    No           95.0            95.0
7    Srirangam           36    No           96.8            96.8
8  Pondicherry           39   Yes          102.2           102.2


Select only the first three rows of the dataframe d1. 


In [150]:
first_three = d1.head(3)

print(first_three)

         city  Temperature  Temperature_F
0  Chandigarh           15           59.0
1       Delhi           22           71.6
2      Kanpur           20           68.0


Select all the rows and last two columns in the dataframe.




In [152]:
last_two_cols = d1.iloc[:, -2:]

print(last_two_cols)

   Temperature  Temperature_F
0           15           59.0
1           22           71.6
2           20           68.0
3           26           78.8
4           -2           28.4


## Groupby

In [155]:
# Create a dataframe using dictionary of your choice

# data = 


data = {
    'Item': ['Espresso', 'Latte', 'Cappuccino', 'Americano'],
    'Price': [2.50, 3.75, 3.50, 2.75],
    'In_Stock': [True, True, False, True]
}

inventory_df = pd.DataFrame(data)
print(inventory_df)

         Item  Price  In_Stock
0    Espresso   2.50      True
1       Latte   3.75      True
2  Cappuccino   3.50     False
3   Americano   2.75      True


In [154]:
# Use Groupby of single column with aggregate sum()
stock_sum = inventory_df.groupby('In_Stock')['Price'].sum()

print(stock_sum)



In_Stock
False    3.5
True     9.0
Name: Price, dtype: float64


In [156]:
# Use Groupby of single column with aggregate count()

stock_count = inventory_df.groupby('In_Stock')['Item'].count()

print(stock_count)

In_Stock
False    1
True     3
Name: Item, dtype: int64


In [157]:
# Use Groupby of single column with aggregate min() and max()


stock_min_max = inventory_df.groupby('In_Stock')['Price'].agg(['min', 'max'])

print(stock_min_max)

          min   max
In_Stock           
False     3.5  3.50
True      2.5  3.75


In [158]:
# Use Groupby of any 2 columns with aggregate mean()


multi_group_mean = inventory_df.groupby(['In_Stock', 'Item'])['Price'].mean()

print(multi_group_mean)

In_Stock  Item      
False     Cappuccino    3.50
True      Americano     2.75
          Espresso      2.50
          Latte         3.75
Name: Price, dtype: float64


In [159]:

data = {
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Clothing', 'Clothing', 'Clothing'],
    'Store_Location': ['North', 'South', 'North', 'North', 'South', 'North'],
    'Price': [500, 700, 450, 25, 40, 30]
}

df_sales = pd.DataFrame(data)


grouped_stats = df_sales.groupby(['Category', 'Store_Location'])['Price'].agg(['min', 'max'])

print(grouped_stats)

                            min  max
Category    Store_Location          
Clothing    North            25   30
            South            40   40
Electronics North           450  500
            South           700  700


## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [161]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')






print a

In [162]:

print(a)


DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')


What is the len of a?

In [163]:
print(len(a))



457


What is the type of a?

In [164]:
print(type(a))




<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
